apiVersion: v1
kind: Service
metadata:
  name: letssee555
spec:
  selector:
    app: letssee555
  ports:
  - name: web
    nodePort: 30084
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
